# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(421, 553)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(194, 198, 198);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_del = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del.setGeometry(QtCore.QRect(30, 150, 181, 51))
        self.btn_del.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_del.setObjectName("btn_del")
        self.btn_ac = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ac.setGeometry(QtCore.QRect(220, 150, 181, 51))
        self.btn_ac.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_ac.setObjectName("btn_ac")
        self.btn_union = QtWidgets.QPushButton(self.centralwidget)
        self.btn_union.setGeometry(QtCore.QRect(30, 210, 81, 51))
        self.btn_union.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_union.setObjectName("btn_union")
        self.btn_interseccion = QtWidgets.QPushButton(self.centralwidget)
        self.btn_interseccion.setGeometry(QtCore.QRect(130, 210, 81, 51))
        self.btn_interseccion.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_interseccion.setObjectName("btn_interseccion")
        self.btn_a = QtWidgets.QPushButton(self.centralwidget)
        self.btn_a.setGeometry(QtCore.QRect(320, 210, 81, 51))
        self.btn_a.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_a.setObjectName("btn_a")
        self.btn_resta = QtWidgets.QPushButton(self.centralwidget)
        self.btn_resta.setGeometry(QtCore.QRect(220, 210, 81, 51))
        self.btn_resta.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_resta.setObjectName("btn_resta")
        self.btn_not = QtWidgets.QPushButton(self.centralwidget)
        self.btn_not.setGeometry(QtCore.QRect(320, 270, 81, 51))
        self.btn_not.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_not.setObjectName("btn_not")
        self.btn_and = QtWidgets.QPushButton(self.centralwidget)
        self.btn_and.setGeometry(QtCore.QRect(130, 270, 81, 51))
        self.btn_and.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_and.setObjectName("btn_and")
        self.btn_x = QtWidgets.QPushButton(self.centralwidget)
        self.btn_x.setGeometry(QtCore.QRect(30, 270, 81, 51))
        self.btn_x.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_x.setObjectName("btn_x")
        self.btn_or = QtWidgets.QPushButton(self.centralwidget)
        self.btn_or.setGeometry(QtCore.QRect(220, 270, 81, 51))
        self.btn_or.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_or.setObjectName("btn_or")
        self.btn_relacional = QtWidgets.QPushButton(self.centralwidget)
        self.btn_relacional.setGeometry(QtCore.QRect(320, 330, 81, 51))
        self.btn_relacional.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_relacional.setObjectName("btn_relacional")
        self.btn_llavecerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_llavecerrar.setGeometry(QtCore.QRect(130, 330, 81, 51))
        self.btn_llavecerrar.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_llavecerrar.setObjectName("btn_llavecerrar")
        self.btn_llaveabrir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_llaveabrir.setGeometry(QtCore.QRect(30, 330, 81, 51))
        self.btn_llaveabrir.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_llaveabrir.setObjectName("btn_llaveabrir")
        self.btn_birelaccional = QtWidgets.QPushButton(self.centralwidget)
        self.btn_birelaccional.setGeometry(QtCore.QRect(220, 330, 81, 51))
        self.btn_birelaccional.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_birelaccional.setObjectName("btn_birelaccional")
        self.btn_equiv = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equiv.setGeometry(QtCore.QRect(320, 390, 81, 51))
        self.btn_equiv.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_equiv.setObjectName("btn_equiv")
        self.btn_conjB = QtWidgets.QPushButton(self.centralwidget)
        self.btn_conjB.setGeometry(QtCore.QRect(130, 390, 81, 51))
        self.btn_conjB.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_conjB.setObjectName("btn_conjB")
        self.btn_conjA = QtWidgets.QPushButton(self.centralwidget)
        self.btn_conjA.setGeometry(QtCore.QRect(30, 390, 81, 51))
        self.btn_conjA.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_conjA.setObjectName("btn_conjA")
        self.btn_conjC = QtWidgets.QPushButton(self.centralwidget)
        self.btn_conjC.setGeometry(QtCore.QRect(220, 390, 81, 51))
        self.btn_conjC.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_conjC.setObjectName("btn_conjC")
        self.btn_igual = QtWidgets.QPushButton(self.centralwidget)
        self.btn_igual.setGeometry(QtCore.QRect(320, 450, 81, 51))
        self.btn_igual.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_igual.setObjectName("btn_igual")
        self.btn_q = QtWidgets.QPushButton(self.centralwidget)
        self.btn_q.setGeometry(QtCore.QRect(130, 450, 81, 51))
        self.btn_q.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_q.setObjectName("btn_q")
        self.btn_p = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p.setGeometry(QtCore.QRect(30, 450, 81, 51))
        self.btn_p.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_p.setObjectName("btn_p")
        self.btn_r = QtWidgets.QPushButton(self.centralwidget)
        self.btn_r.setGeometry(QtCore.QRect(220, 450, 81, 51))
        self.btn_r.setStyleSheet("background-color: rgb(226, 231, 231);")
        self.btn_r.setObjectName("btn_r")
        self.resultado = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(30, 60, 371, 79))
        self.resultado.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.resultado.setReadOnly(True)
        self.resultado.setPlainText("")
        self.resultado.setBackgroundVisible(False)
        self.resultado.setObjectName("resultado")
        self.operacion = QtWidgets.QLineEdit(self.centralwidget)
        self.operacion.setGeometry(QtCore.QRect(30, 10, 371, 41))
        self.operacion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.operacion.setText("")
        self.operacion.setAlignment(QtCore.Qt.AlignCenter)
        self.operacion.setObjectName("operacion")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora Binaria"))
        self.btn_del.setText(_translate("MainWindow", "DEL"))
        self.btn_ac.setText(_translate("MainWindow", "AC"))
        self.btn_union.setText(_translate("MainWindow", "U"))
        self.btn_interseccion.setText(_translate("MainWindow", "∩"))
        self.btn_a.setText(_translate("MainWindow", "A"))
        self.btn_resta.setText(_translate("MainWindow", "-"))
        self.btn_not.setText(_translate("MainWindow", "  ¬"))
        self.btn_and.setText(_translate("MainWindow", "^"))
        self.btn_x.setText(_translate("MainWindow", "x"))
        self.btn_or.setText(_translate("MainWindow", "v"))
        self.btn_relacional.setText(_translate("MainWindow", "→"))
        self.btn_llavecerrar.setText(_translate("MainWindow", "}"))
        self.btn_llaveabrir.setText(_translate("MainWindow", "{"))
        self.btn_birelaccional.setText(_translate("MainWindow", "↔"))
        self.btn_equiv.setText(_translate("MainWindow", "≡"))
        self.btn_conjB.setText(_translate("MainWindow", "B"))
        self.btn_conjA.setText(_translate("MainWindow", "A"))
        self.btn_conjC.setText(_translate("MainWindow", "C"))
        self.btn_igual.setText(_translate("MainWindow", "="))
        self.btn_q.setText(_translate("MainWindow", "q"))
        self.btn_p.setText(_translate("MainWindow", "p"))
        self.btn_r.setText(_translate("MainWindow", "r"))
        self.resultado.setPlaceholderText(_translate("MainWindow", "Resultado"))
        self.operacion.setPlaceholderText(_translate("MainWindow", "Operación a realizar"))

